import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Register } from '../models/register.model';

//generated by ng g s service/register
@Injectable({
  providedIn: 'root'
})
export class RegisterService {
formData:Register;

  constructor() { }
}
