import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Register } from '../models/register.model';

//generated by ng g s service/register
@Injectable({
  providedIn: 'root'
})
export class RegisterService {
  formData: Register;

  readonly rootURL = "https://localhost:44359/api/"
  constructor(private http: HttpClient) { }

  //Load and Reload data
  loadUsers() {
    return this.http.get(this.rootURL + 'Users');
  }

  InsertUser() {
    return this.http.post(this.rootURL + '', this.formData);
  }

  UpdateUser() {
    return this.http.post(this.rootURL + 'Users/' + this.formData.Id, this.formData);
  }

  DeleteUser(Id){
    return this.http.delete(this.rootURL+'Users/'+Id);
  }
}
